Tweak box size and update variable pitch
sashimacs/os1-theme pull request #4
Opened 2023-04-11 15:28 UTC by rymndhng

Thanks for this lovely colorscheme. I'd like to propose two minor fixes.

### fix: magit-section-heading faces respect s-variable-pitch

Solarized has a configuration option to turn on variable pitch faces via
`solarized-use-variable-pitch`. See https://github.com/bbatsov/solarized-emacs/blob/master/solarized-faces.el#L324-L325

### fix: Reduce mode-line box line-width to 1

For the vanilla modeline user, I'd like the width to be a reasonable size. 

| Before | After |
|--|--|
|<img width="470" alt="Screenshot 2023-04-11 at 8 23 57 AM" src="https://user-images.githubusercontent.com/1694040/231212427-a16bc734-df3b-4513-8b83-da9ebf164906.png">|<img width="453" alt="Screenshot 2023-04-11 at 8 24 09 AM" src="https://user-images.githubusercontent.com/1694040/231212323-b08b018f-e07b-4d52-a7b8-96c7948bf770.png">|

After:

2023-04-11 16:43 UTC, sashimacs requested changes
Thanks! I agree we shouldn't force the modeline padding on users so I've added it as a customization option instead, defaulting to `1`. Would you mind updating to incorporate that here?

2023-04-11 16:43 UTC, sashimacs commented on os1-customized.el
> +                 :box (:line-width 1 :color ,base02)))))
```suggestion
                 :box (:line-width ,os1-modeline-padding :color ,base02)))))
```

2023-04-11 16:43 UTC, sashimacs commented on os1-customized.el
> +                 :box (:line-width 1 :color ,hl-light)))))
```suggestion
                 :box (:line-width ,os1-modeline-padding :color ,hl-light)))))
```

2023-04-12 05:29 UTC, rymndhng commented
> Thanks! I agree we shouldn't force the modeline padding on users so I've added it as a customization option instead, defaulting to 1. Would you mind updating to incorporate that here?

absolutely !

2023-04-12 05:30 UTC, rymndhng commented on os1-customized.el
> +                 :box (:line-width 1 :color ,base02)))))
fixed from merge against base branch

2023-04-12 05:31 UTC, rymndhng commented
I've reduced the scope of this ticket to the change to `s-variable-pitch` since the other changes are already on `main`.

2023-04-12 11:14 UTC, merged

2023-04-12 11:15 UTC, sashimacs commented
Thank you!